name: mg_common_game
description: Monthly Games 공통 게임 엔진 모듈
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.14.0
  firebase_core: ^2.24.0
  firebase_analytics: ^10.7.0
  cloud_firestore: ^4.13.0
  firebase_auth: ^4.15.0
  get_it: ^7.6.4
  injectable: ^2.3.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
